### ISSUE TITLE
Installation is broken in 0.0.2

### ISSUE THREAD

**Issue by yprez** [dfm/feedfinder2#5]
```
$ mktmpenv 
New python executable in tmp-ec9bbfb1a8576f4/bin/python
Installing setuptools, pip, wheel...done.
This is a temporary environment. It will be deleted when you run 'deactivate'.

$ pip install feedfinder2
Collecting feedfinder2
  Downloading feedfinder2-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-iZmsj6/feedfinder2/setup.py", line 8, in <module>
        import feedfinder2
      File "feedfinder2.py", line 9, in <module>
        import requests
    ImportError: No module named requests

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-iZmsj6/feedfinder2
```

The requirements are imported before setup.py processes the `install_requires` section, because of the `import feedfinder2` line in setup.py.

The breaking change is: https://github.com/dfm/feedfinder2/commit/bf354c151eb0292b3117ac363ffe3195409475c4#diff-2eeaed663bd0d25b7e608891384b7298R8

**Comment by yprez** [comment]
@dfm thanks for the quick fix!

**Comment by dfm** [comment]
This should work now in version 0.0.3. Let me know if you have other problems.

**Comment by yprez** [comment]
@dfm thanks for the quick reply.

Still doesn't work unfortunately... (on 0.0.3)

```
$ pip install feedfinder2
Collecting feedfinder2
  Using cached feedfinder2-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-_RrGYT/feedfinder2/setup.py", line 8, in <module>
        import feedfinder2
      File "feedfinder2.py", line 17, in <module>
        import requests
    ImportError: No module named requests

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_RrGYT/feedfinder2
```

**Comment by dfm** [comment]
Oh duh! I forgot the most important part! Give it another shot...

**Comment by yprez** [comment]
Works now. Thanks!

**Comment by menguzat** [comment]
I'm having the same issue with 0.0.4
 pip install feedfinder2
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting feedfinder2
  Downloading feedfinder2-0.0.4.tar.gz (3.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\tmp\pip-install-wny93au0\feedfinder2_2600a0c3a234420babca44bcb03317d9\setup.py", line 15, in <module>
          import feedfinder2
      ModuleNotFoundError: No module named 'feedfinder2'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
